### ISSUE TITLE
Program exits and last logs are not sent to Discord

### ISSUE THREAD

**Issue by aidanmelen** [abrahammurciano/discord-lumberjack#35]
I have noticed some interesting behavior. if the program exits normally then the last last few log events are not sent to Discord. However, you if place a `time.sleep(10)` at the end, there is a better chance the logs are flushed and sent to Discord.

**Comment by aidanmelen** [comment]
perhaps [_assert_messages_sent](https://github.com/abrahammurciano/discord-lumberjack/blob/main/discord_lumberjack/handlers/discord_handler.py#L127-L137) shouldn't only exist for testing purposes

**Comment by abrahammurciano** [comment]
That's a great observation! Thanks for your valuable input. Let me think about it, and I'll update you here soon

**Comment by abrahammurciano** [comment]
See this:

https://stackoverflow.com/questions/70733909/can-i-run-cleanup-code-in-daemon-threads-in-python

In the meantime, since I suspect there is no good solution to my question, I guess I'll have to expose a way for you (the user) to wait for messages to send before exiting.

**Comment by abrahammurciano** [comment]
btw, feel free to join my discord server. you can ask questions/make suggestions about this project over there
https://discord.com/invite/mzhSRnnY78

**Comment by abrahammurciano** [comment]
There was a quite elegant solution posted to the SO link above, I'll be implementing it for v1.0.5 soon, and thus will be deprecating the flush method.
